# Generated by Django 5.2.1 on 2025-05-27 08:18

from django.db import migrations
from decimal import Decimal


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    name_field = Plan._meta.get_field("name")
    term_field = Plan._meta.get_field("plan_term")
    plan_name_choices = [choice[0] for choice in name_field.choices]
    plan_term_choices = [choice[0] for choice in term_field.choices]
    PRICING = {
        "basic": {
            "monthly": 10,
            "quaterly": 27,  # 10%
            "half_yearly": 51,  # 15%
            "yearly": 96,  # 20%
        },
        "pro": {
            "monthly": 20,
            "quaterly": 54,  # 10%
            "half_yearly": 102,  # 15%
            "yearly": 192,  # 20%
        },
        "enterprise": {
            "monthly": 40,
            "quaterly": 108,  # 10%
            "half_yearly": 204,  # 15%
            "yearly": 384,  # 20%
        },
    }

    default_plans = []
    for name in plan_name_choices:
        for term in plan_term_choices:
            default_plans.append(
                Plan(
                    name=name,
                    plan_term=term,
                    description="",
                    price=Decimal(PRICING[name][term]),
                    is_active=True,
                )
            )

    Plan.objects.bulk_create(default_plans)


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_plans, migrations.RunPython.noop)]
