# Generated by Django 5.2.1 on 2025-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_unique_active_subscription_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
